### ISSUE TITLE
Fetch in modules

### ISSUE THREAD

**Issue by RooyyDoe** [StefanGerrits2/web-app-from-scratch-1920#11]
- Je kan je fetch in een module schrijven, zodat je hem elke keer kan hergebruiken op die manier vanuit die module. ( kortere code! :DD )

https://codeburst.io/fetch-api-was-bringing-darkness-to-my-codebase-so-i-did-something-to-illuminate-it-7f2d8826e939

**Comment by RooyyDoe** [comment]
Dit gebruikt ook een bepaalde error handeling waar Joost het over had in de klas

**Comment by StefanGerrits2** [comment]
Thanks, ik heb deze verwerkt in mijn code! Ik vind dit inderdaad een stuk beter omdat de error handeling nu beter is en daarnaast vind ik de fetch module ook prettig om mee te werken.
