### ISSUE TITLE
Creating elements instead of innerHTML

### ISSUE THREAD

**Issue by RooyyDoe** [StefanGerrits2/web-app-from-scratch-1920#12]
Van regel 56 t/m 71 heb jij deze code: 

```

// Create HTML template and render it
function createList(data) {
    const cardsDiv = document.getElementById('cardsDiv')
    currentPage.innerHTML = `Page: ${page}`
    // Create a card for each beer
    const cards = data.map(data => {
        return `
            <article id="cardDiv">
                <h2 class="name">${data.name}</h2>
                <img src="${data.image_url}"/>
                <p class="tagline">"${data.tagline}"</p>
            </article>
        `;
    }).join('');
    cardsDiv.innerHTML = cards
}

```

Inplaats van deze code kan je gebruik maken van textContent hier zijn een paar artikelen over de verschillen van innerHTML/textContent/innerText:

- [Is-textcontent-better?](https://blog.cloudboost.io/why-textcontent-is-better-than-innerhtml-and-innertext-9f8073eb9061)
- [Everything Explained(With examples)](http://xahlee.info/js/js_textContent_innerHTML_innerText_nodeValue.html)
- [video](https://www.youtube.com/watch?v=1UsllDMhvN4)

**Ik doe het op deze manier:**

Ik heb een aparte functie via ES6 modules die de "card" creëert ik maak de elementen aan en geef het hoofd element een `class` mee en aan de `h1`/`p` geef ik de data mee hoe jij dat hebt gedaan met de template literals in je innerHTML.

Uiteindelijk append je de `h1` en `p` aan de card toe en kan je aan de div class de verdere css geven.

```

export default function insertGames(data) {
    
    const card = document.createElement('div'),
            h1 = document.createElement('h1'),
            p = document.createElement('p');
                    
    card.setAttribute('class', 'card')

    h1.textContent = data.name;
    p.textContent = data.slug;

    card.appendChild(h1)
    card.appendChild(p)

    return card;

}

```

Mijn code: 

- [Look at the showResults function](https://github.com/RooyyDoe/web-app-from-scratch-1920/blob/master/week1/public/js/main.js)
- [Card creator](https://github.com/RooyyDoe/web-app-from-scratch-1920/blob/master/week1/public/modules/createCard.js)

Bronnen voor textContent:
- [Quick peak at W3S](https://www.w3schools.com/jsref/prop_node_textcontent.asp)
- [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent)
- [Video](https://www.youtube.com/watch?v=XW9ncbnfzZo)

**Comment by StefanGerrits2** [comment]
Thanks for your amazing feedback!

Will look into this soon, I'll keep you updated :)

**Comment by StefanGerrits2** [comment]
I've implemented this in my code. This is indeed a better way to do it and it's more secure instead of innerHTML.

If you want to check it out you can check my repo ;)
