### ISSUE TITLE
Consider bundling global variables

### ISSUE THREAD

**Issue by Razpudding** [StefanGerrits2/web-app-from-scratch-1920#15]
page, topic and limit are basically settings for your app.

You could consider making an App object and giving it those three properties. You could also put the functions load and pagionationnext inside the app as methods to make it self contained.

**Comment by StefanGerrits2** [comment]
I removed topic and limit since I don't use them since topic isn't even changeable and I set the limit myself which won't change.

I now only keep page as this is a state which needs to be remembered to know what data to use.
