### ISSUE TITLE
Little confusing what happens in your actor diagram at Router and Render

### ISSUE THREAD

**Issue by TomasStolp** [StefanGerrits2/web-app-from-scratch-1920#16]
In your Router environment you describe ```Render.overview()``` etc and then Router.handle(). It's a little confusing what the Render.overview() does in the router because it's defined as wel in the Render() environment.

Might be a typo, but it seems a little odd to me which functions take place where.

**Comment by StefanGerrits2** [comment]
Yes this is a typo, will fix it, thanks
