### ISSUE TITLE
What happens within the Render.overview() function?

### ISSUE THREAD

**Issue by TomasStolp** [StefanGerrits2/web-app-from-scratch-1920#20]
What happens inside the Render.overview() function?

I can guess without looking, that you render the page as a whole within that function. 

I might be wrong, but if I'm not, maybe you can separate that logic into even smaller, more pure functions.

**Comment by StefanGerrits2** [comment]
Yes it renders the whole page within that function. I'm planning to seperate that into smaller functions. Thanks for your feedback
