### ISSUE TITLE
Your app works like I would expect, I think a nice feature would be:

### ISSUE THREAD

**Issue by TomasStolp** [StefanGerrits2/web-app-from-scratch-1920#21]
A nice feature could be that the user can filter beers by alcohol percentage or by some kind of beer. I don't think that's too hard to implement that, but it would be quite awesome.

**Comment by StefanGerrits2** [comment]
Yes that would be awesome!, but for now I've added a feature which shows related beers that are around the same alchol by volume on the detail page.

I might add a filter system if I've got time left.
