### ISSUE TITLE
Rubric - WAFS

### ISSUE THREAD

**Issue by RooyyDoe** [StefanGerrits2/web-app-from-scratch-1920#23]
- Code consistentie kan je even kijken naar de `;`. Die is nog niet overal consistent.

- Meer code comments voor sneller begrip

- Modules komen nog niet overeen met de actor Diagram. Maar hiermee ben je waarschijnlijk nog steeds bezig

- Je gebruikt Fetch en een `.then` chain. Dus volgens mij haal je async data op.

- Tot nu toe zie ik 1 `.map` ( Weet niet precies wat je hier doet ) //Code comments

- Je maakt gebruik van een router library. Dit is super nice, misschien is het handig om een template engine te gebruiken om op deze manier minder lange code te hebben.

- De flow van je applicatie is super nice!!!

- Heb je feedback verwerkt in de app? of moet je hier nog mee bezig gaan. volgens mij heeft dit te maken met error handeling etc.

**Comment by StefanGerrits2** [comment]
Thanks!

* Ik heb eslint toegevoegd voor de nodige stijlfouten zoals de `;`
* Comments zal ik toevoegen
* Ben inderdaad nog met mijn modules en diagrammen bezig!
* Ik gebruik nu tiny mustache als templating engine! Dit werkt super fijn.
* Ik heb nu ook feedback toegevoegd als data wordt gefetched (een loading animation)
