### ISSUE TITLE
What if you needed to render something else?

### ISSUE THREAD

**Issue by TomasStolp** [StefanGerrits2/web-app-from-scratch-1920#3]
Everything is going well, but what would your approach be if you were to render out something else then a list?

https://github.com/StefanGerrits2/web-app-from-scratch-1920/blob/e9b3d63e0f2562461d2aa13fcaf8d2437054330c/index.js#L7-L17

**Comment by StefanGerrits2** [comment]
I don't know yet, I wrote this just to render the overview page with data. I need to render something different when the user clicks on a card, for example the detail page needs to be rendered. I will write a different function for this with a given route which I will be working on later.
