### ISSUE TITLE
Leerpunten in README.md

### ISSUE THREAD

**Issue by RooyyDoe** [StefanGerrits2/web-app-from-scratch-1920#8]
- Misschien kan je je eigen leerpunten opschrijven, zodat je aan het eind van dit vak kan zien wat je allemaal heb geleerd ( bewijs voor de leraar )

**Comment by StefanGerrits2** [comment]
Goeie! ik zal deze binnenkort toevoegen aan mijn readme, inderdaad handig als een overzichtje wat ik allemaal heb geleerd.
